---

node-01:
  hosts:
    mmifntcpeprd201:
      ansible_host: mmifntcpeprd201
      ansible_connection: ssh
      ansible_ssh_user: niroy
      ansible_ssh_pass: Omsairam@123
      ansible_python_interpreter: /usr/bin/python3
  vars:
    num: "01"

node-02:
  hosts:
    mmifntcpeprd202:
      ansible_host: mmifntcpeprd202
      ansible_connection: ssh
      ansible_ssh_user: niroy
      ansible_ssh_pass: Omsairam@123
      ansible_python_interpreter: /usr/bin/python3
  vars:
    num: "02"

nodes:
  children:
    node-01:
    node-02: