- name: get files
  find:
    age: -2h
    file_type: any
    paths: "path{{ inventory_hostname}}"
  register: find_output

- name: create files list
  set_fact:
    files: '{{ files + [item.path] }}'
  with_items: "{{ find_output.files}}"

- debug:
    verbosity: 2
    var: files

- name: fetch files
  fetch:
    src: "{{ item }}"
    dest: "./logs/prefix-{{ inventory_hostname }}"
  register: fetch_output

- debug:
    verbosity: 2
    var: fetch_output